# Travis file for build checks
sudo: required

language: java

jdk:
  - oraclejdk8

services:
  - docker

before_install:
  - docker pull elasticsearch
  - docker run -d -p 9200:9200 -p 9300:9300 elasticsearch

script:
  - mvn clean install
