# Travis file for build checks
language: java
jdk:
  - oraclejdk8
sudo: required
service:
  - docker
before_install:
- docker pull elasticsearch
- docker run -d -p 9200:9200 -p 9300:9300 elasticsearch
script: mvn clean install

