elasticsearch:
  host: "localhost"
  port: 9200

defaultName: "swagger"

rabbit:
  host: localhost #gatekeeper-preprod-mq.cloud.appctest.com
  port: 5672
  user: guest #rabbit
  pass: guest #runrabbitrun